### ISSUE TITLE
Parse Substrate's Metadata V14

### ISSUE THREAD

**Issue by Lohann** [rankanizer/polkadart#14]
## Description
Metadata parsing impl and type-conversion from network json schema to Types Model.

## Tasks:
- [x] Substrate Metadata definitions: (**base** and **v9 - v14**)
- [x] Xcm Encode / Decode
- [x] Test Cases for verifying chain data
- [x] Chain specific schemas definitions
- [x] Testing Old Type Registry and Type Exp
- [x] More Test cases to reach code coverage of minimum 99%

## Acceptance Criteria:
- Minimum 99% Code Coverage Required.
- Parsing of all chain blocks and events without any hiccups

**Comment by LuizaJurimetric** [comment]
Blocked due to test cases for substrate's metadata.
